# -*- coding: utf-8 -*-
"""Milestone2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uF6SkoPiL7d8M10DRyE2Q5lT0fX09LGc
"""

pip install scikit-surprise

import pandas as pd

data = pd.read_csv("/content/cleaned_ecommerce_dataset.csv")

print(data.head())
print("Dataset shape:", data.shape)

from surprise import Dataset, Reader

import pandas as pd

data = pd.read_csv("/content/cleaned_ecommerce_dataset.csv")

# Define rating scale using 'interaction' column
reader = Reader(
    rating_scale=(1, int(data['interaction'].max()))
)

dataset = Dataset.load_from_df(
    data[['user_id', 'item_id', 'interaction']],
    reader
)

from surprise.model_selection import train_test_split

trainset, testset = train_test_split(
    dataset,
    test_size=0.2,
    random_state=42
)

from surprise import SVD

svd_model = SVD(
    n_factors=50,
    n_epochs=20,
    lr_all=0.005,
    reg_all=0.02,
    random_state=42
)

svd_model.fit(trainset)

print("SVD model trained successfully")

from surprise import accuracy

predictions = svd_model.test(testset)

rmse = accuracy.rmse(predictions)
mae = accuracy.mae(predictions)

def recommend_products_svd(model, data, user_id, N=5):
    all_items = data['item_id'].unique()

    predictions = [
        (item, model.predict(user_id, item).est)
        for item in all_items
    ]

    predictions.sort(key=lambda x: x[1], reverse=True)

    return [item for item, _ in predictions[:N]]

sample_user = data['user_id'].iloc[0]

recommendations = recommend_products_svd(
    svd_model,
    data,
    sample_user,
    N=5
)

# Create a mapping from item_id to category
product_to_category = data.set_index('item_id')['category'].to_dict()

recommended_with_categories = []

for pid in recommendations:
    category = product_to_category.get(pid, "Unknown Category")
    recommended_with_categories.append(f"{pid} ({category})")
print("User:", sample_user)
print("Recommended products with categories:")

for product in recommended_with_categories:
    print(product)

