# -*- coding: utf-8 -*-
"""preprocessinf code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yoSlo-5Ha9blQwEcezgsyxu-1hmtSft1
"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("/content/events.csv.csv")

# Show basic info
print(df.info())

# Remove duplicates
df.drop_duplicates(inplace=True)

# Handle missing values
df.dropna(inplace=True)

# Rename columns (if needed)
df.rename(columns={
    'visitorid': 'userId',  # Corrected column name
    'itemid': 'productId'   # Corrected column name
    # Removed 'rating' as it does not exist in the original dataset
}, inplace=True)

# Convert datatypes
df['userId'] = df['userId'].astype(str)
df['productId'] = df['productId'].astype(str)

print("Cleaned Data Shape:", df.shape)

!pip install scikit-surprise

from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split

# Create a 'rating' column from the 'event' column
# Assign numerical ratings based on event type
event_to_rating = {
    'view': 1,
    'addtocart': 2,
    'transaction': 3
}
df['rating'] = df['event'].map(event_to_rating)

# Drop rows where 'event' was not one of the mapped types (if any) or if 'rating' became NaN
df.dropna(subset=['rating'], inplace=True)

# Convert rating to integer type
df['rating'] = df['rating'].astype(int)

# Define the rating scale based on the assigned values
reader = Reader(rating_scale=(1, 3)) # Max rating is 3 from 'transaction' event

# Load the dataset with userId, productId, and the newly created rating
data = Dataset.load_from_df(df[['userId','productId','rating']], reader)

trainset, testset = train_test_split(data, test_size=0.2)

model = SVD()
model.fit(trainset)

def recommend(user_id, n=5):
    products = df['productId'].unique()
    predictions = []

    for product in products:
        pred = model.predict(user_id, product)
        predictions.append((product, pred.est))

    predictions.sort(key=lambda x: x[1], reverse=True)
    return predictions[:n]

print(recommend('U123'))